### ISSUE TITLE
I get an error after I updated to 0.5.0

### ISSUE THREAD

**Issue by J0NNYZER0** [webpack-contrib/mini-css-extract-plugin#323]
/Users/jonortiz/github/ludwigjs/node_modules/webpack-cli/bin/cli.js:244
				throw err;
				^

Error: Cannot find module 'mini-css-extract-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (/Users/jonortiz/github/ludwigjs/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/jonortiz/github/ludwigjs/webpack.prod.config.js:4:26)
    at Module._compile (/Users/jonortiz/github/ludwigjs/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (/Users/jonortiz/github/ludwigjs/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/Users/jonortiz/github/ludwigjs/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/Users/jonortiz/github/ludwigjs/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /Users/jonortiz/github/ludwigjs/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/jonortiz/github/ludwigjs/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/Users/jonortiz/github/ludwigjs/node_modules/webpack-cli/bin/cli.js:241:39)
    at Object.parse (/Users/jonortiz/github/ludwigjs/node_modules/webpack-cli/node_modules/yargs/yargs.js:563:18)
    at /Users/jonortiz/github/ludwigjs/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/Users/jonortiz/github/ludwigjs/node_modules/webpack-cli/bin/cli.js:538:3)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/jonortiz/github/ludwigjs/node_modules/webpack/bin/webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:308:19)

**Comment by evilebottnawi** [comment]
Try to clean cache `yarn`/`npm` cache clean
