### ISSUE TITLE
Cannot find module 'mini-css-extract-plugin/src/CssDependency'

### ISSUE THREAD

**Issue by jrwpatterson** [webpack-contrib/mini-css-extract-plugin#584]
- Operating System:  MacOs
- Node Version:12.18.3
- NPM Version:6.14.6
- webpack Version: 5.0-beta.29
- mini-css-extract-plugin Version: 0.11.1

### Expected Behavior

No Warnings

### Actual Behavior
Since upgrading from 0.11.0 to 0.11.1

My console is getting spammed with [webpack.cache.PackFileCacheStrategy] Restoring failed for ResolverCachePlugin ... Error: Cannot find module 'mini-css-extract-plugin/src/CssDependency'

![Screen Shot 2020-09-10 at 6 50 16 pm](https://user-images.githubusercontent.com/18130488/92717739-145c4980-f3a4-11ea-879f-acaf04fbf936.png)

**Comment by leaves4j** [comment]
https://github.com/webpack-contrib/mini-css-extract-plugin/blob/15657065a392b375edcb3876d726ea1a59c4b0b6/src/CssDependency.js#L44

**Comment by evilebottnawi** [comment]
Please create reproducible test repo

**Comment by evilebottnawi** [comment]
@leeonfield Each fix should have test(s)

**Comment by leeonfield** [comment]
> Please create reproducible test repo

[reproduce repo](https://github.com/leeonfield/issue-test-repo/tree/master/mini-css-extract-plugin-issues-584)

**Comment by leeonfield** [comment]
> @leeonfield Each fix should have test(s)

sorry about that, here is the[reproducible test repo](https://github.com/leeonfield/issue-test-repo/tree/master/mini-css-extract-plugin-issues-584)

**Comment by jrwpatterson** [comment]
Cheers @leeonfield I was asleep when you did that!

**Comment by evilebottnawi** [comment]
Fixed in master, release will be soon
